import { db } from "@/lib/db";
import { auditLogs } from "@/db/schema";

/**
 * Audit log actions recorded across the application.
 * Append-only trail: actor, entity, entity id, timestamp, safe metadata.
 * Passwords, hashes and secrets are NEVER written to metadata.
 */
export const AUDIT_ACTIONS = {
  PATIENT_CREATED: "PATIENT_CREATED",
  PATIENT_UPDATED: "PATIENT_UPDATED",
  PATIENT_ARCHIVED: "PATIENT_ARCHIVED",
  PATIENT_REACTIVATED: "PATIENT_REACTIVATED",
  APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
  APPOINTMENT_RESCHEDULED: "APPOINTMENT_RESCHEDULED",
  APPOINTMENT_STATUS_CHANGED: "APPOINTMENT_STATUS_CHANGED",
  VISIT_CREATED: "VISIT_CREATED",
  VISIT_COMPLETED: "VISIT_COMPLETED",
  VISIT_CORRECTION_APPENDED: "VISIT_CORRECTION_APPENDED",
  PATIENT_CONTACTED: "PATIENT_CONTACTED",
  PAYMENT_CREATED: "PAYMENT_CREATED",
  CHARGE_CREATED: "CHARGE_CREATED",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",
  USER_PASSWORD_RESET: "USER_PASSWORD_RESET",
  CLINIC_SETTINGS_UPDATED: "CLINIC_SETTINGS_UPDATED",
  // Services & categories
  SERVICE_CREATED: "SERVICE_CREATED",
  SERVICE_UPDATED: "SERVICE_UPDATED",
  SERVICE_ARCHIVED: "SERVICE_ARCHIVED",
  SERVICE_REACTIVATED: "SERVICE_REACTIVATED",
  SERVICE_CATEGORY_CREATED: "SERVICE_CATEGORY_CREATED",
  SERVICE_CATEGORY_UPDATED: "SERVICE_CATEGORY_UPDATED",
  SERVICE_CATEGORY_ARCHIVED: "SERVICE_CATEGORY_ARCHIVED",
  SERVICE_CATEGORY_REACTIVATED: "SERVICE_CATEGORY_REACTIVATED",
  // Work items
  WORK_ITEM_CREATED: "WORK_ITEM_CREATED",
  WORK_ITEM_UPDATED: "WORK_ITEM_UPDATED",
  WORK_ITEM_CANCELLED: "WORK_ITEM_CANCELLED",
  // Treasury
  CASH_ACCOUNT_CREATED: "CASH_ACCOUNT_CREATED",
  CASH_ACCOUNT_UPDATED: "CASH_ACCOUNT_UPDATED",
  CASH_ACCOUNT_ARCHIVED: "CASH_ACCOUNT_ARCHIVED",
  CASH_ACCOUNT_REACTIVATED: "CASH_ACCOUNT_REACTIVATED",
  EXPENSE_CATEGORY_CREATED: "EXPENSE_CATEGORY_CREATED",
  EXPENSE_CATEGORY_UPDATED: "EXPENSE_CATEGORY_UPDATED",
  EXPENSE_CATEGORY_ARCHIVED: "EXPENSE_CATEGORY_ARCHIVED",
  EXPENSE_CATEGORY_REACTIVATED: "EXPENSE_CATEGORY_REACTIVATED",
  // Vouchers
  VOUCHER_CREATED: "VOUCHER_CREATED",
  VOUCHER_REVERSED: "VOUCHER_REVERSED",
  VOUCHER_PRINTED: "VOUCHER_PRINTED",
  STATEMENT_PRINTED: "STATEMENT_PRINTED",
  REPORT_PRINTED: "REPORT_PRINTED",
  // Commissions
  COMMISSION_PLAN_SAVED: "COMMISSION_PLAN_SAVED",
  COMMISSION_PLAN_DELETED: "COMMISSION_PLAN_DELETED",
  COMMISSION_GENERATED: "COMMISSION_GENERATED",
  COMMISSION_APPROVED: "COMMISSION_APPROVED",
  COMMISSION_PAID: "COMMISSION_PAID",
  COMMISSION_PAYMENT_REVERSED: "COMMISSION_PAYMENT_REVERSED",
  COMMISSION_REVERSED: "COMMISSION_REVERSED",
  COMMISSION_AMOUNT_SET: "COMMISSION_AMOUNT_SET",
  // Labs
  LAB_CREATED: "LAB_CREATED",
  LAB_UPDATED: "LAB_UPDATED",
  LAB_ARCHIVED: "LAB_ARCHIVED",
  LAB_REACTIVATED: "LAB_REACTIVATED",
  LAB_CASE_CREATED: "LAB_CASE_CREATED",
  LAB_CASE_UPDATED: "LAB_CASE_UPDATED",
  LAB_CASE_INVOICED: "LAB_CASE_INVOICED",
  // Suppliers & materials
  SUPPLIER_CREATED: "SUPPLIER_CREATED",
  SUPPLIER_UPDATED: "SUPPLIER_UPDATED",
  SUPPLIER_ARCHIVED: "SUPPLIER_ARCHIVED",
  SUPPLIER_REACTIVATED: "SUPPLIER_REACTIVATED",
  MATERIAL_CREATED: "MATERIAL_CREATED",
  MATERIAL_UPDATED: "MATERIAL_UPDATED",
  MATERIAL_ARCHIVED: "MATERIAL_ARCHIVED",
  MATERIAL_REACTIVATED: "MATERIAL_REACTIVATED",
  PURCHASE_INVOICE_CREATED: "PURCHASE_INVOICE_CREATED",
  PURCHASE_INVOICE_CANCELLED: "PURCHASE_INVOICE_CANCELLED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export type AuditEntityType =
  | "patient"
  | "appointment"
  | "visit"
  | "contact"
  | "payment"
  | "charge"
  | "user"
  | "settings"
  | "service"
  | "service_category"
  | "work_item"
  | "cash_account"
  | "expense_category"
  | "voucher"
  | "commission"
  | "commission_plan"
  | "lab"
  | "lab_case"
  | "supplier"
  | "material"
  | "purchase_invoice";

export type AuditInput = {
  userId: string;
  action: AuditAction;
  entityType: AuditEntityType;
  entityId: string;
  metadata?: Record<string, unknown>;
};

/** Minimal executor interface shared by the db client and transactions. */
type AuditExecutor = Pick<typeof db, "insert">;

/**
 * Record an audit entry.
 *
 * Pass an open transaction as `executor` to make the audit row part of the
 * SAME atomic commit as the movement it describes (required for financial
 * mutations). Without an executor the global client is used.
 */
export async function recordAudit(
  input: AuditInput,
  executor: AuditExecutor = db
): Promise<void> {
  await executor.insert(auditLogs).values({
    userId: input.userId,
    action: input.action,
    entityType: input.entityType,
    entityId: input.entityId,
    metadata: input.metadata,
  });
}
